name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies for functions
        # Explicitly tell npm install where to find package.json
        run: npm install --prefix functions

      - name: Deploy to Firebase
        # Specify the Firebase project ID and the hosting site name for deployment
        # The default hosting site name is usually the same as the project ID.
        run: firebase deploy --project roast-battle-arena-95827 --site roast-battle-arena-95827 --token ${{ secrets.FIREBASE_TOKEN }}
